-- 001_core_schema_oracle.sql
-- Oracle version (execute as user with access to APP schema).
-- Prereq: schemas/users APP, SILVER, BRONZE and MART already provisioned.

create table app.condominios (
  condominio_id number(19,0) primary key,
  nome_condominio varchar2(255) not null,
  cnpj varchar2(18) not null unique,
  endereco clob,
  cidade varchar2(120) not null,
  estado char(2) not null,
  qtd_unidades number(10,0) not null check (qtd_unidades >= 0),
  data_implantacao date
);

create table app.unidades (
  unidade_id number(19,0) primary key,
  condominio_id number(19,0) not null,
  bloco varchar2(10) not null,
  numero_unidade varchar2(10) not null,
  andar number(10,0),
  area_m2 number(10,2),
  fracao_ideal number(10,6),
  tipo_unidade varchar2(40) not null,
  qtd_quartos number(10,0),
  qtd_vagas_garagem number(10,0),
  data_entrega date,
  constraint fk_unidades_condominio foreign key (condominio_id) references app.condominios(condominio_id),
  constraint uq_unidades_cond_bloco_num unique (condominio_id, bloco, numero_unidade)
);

create table app.moradores (
  morador_id number(19,0) primary key,
  condominio_id number(19,0) not null,
  unidade_id number(19,0),
  nome varchar2(255) not null,
  tipo_morador varchar2(20) not null,
  data_inicio_residencia date,
  telefone varchar2(40),
  email varchar2(255),
  constraint fk_moradores_condominio foreign key (condominio_id) references app.condominios(condominio_id),
  constraint fk_moradores_unidade foreign key (unidade_id) references app.unidades(unidade_id),
  constraint ck_moradores_tipo check (tipo_morador in ('proprietario', 'inquilino'))
);

create table app.fornecedores (
  fornecedor_id number(19,0) primary key,
  razao_social varchar2(255) not null,
  cnpj varchar2(18) not null unique,
  cnae_principal varchar2(10),
  data_abertura date,
  status_rfb varchar2(20),
  cidade varchar2(120),
  estado char(2)
);

create table app.contratos (
  contrato_id number(19,0) primary key,
  condominio_id number(19,0) not null,
  fornecedor_id number(19,0) not null,
  tipo_servico varchar2(255) not null,
  valor_mensal_vigente number(14,2) not null,
  data_inicio date not null,
  data_vencimento date not null,
  indice_reajuste varchar2(10) not null,
  sla_horas_mensais number(10,2),
  status_auditoria_ia varchar2(120),
  constraint fk_contratos_condominio foreign key (condominio_id) references app.condominios(condominio_id),
  constraint fk_contratos_fornecedor foreign key (fornecedor_id) references app.fornecedores(fornecedor_id),
  constraint ck_contratos_indice check (indice_reajuste in ('IPCA', 'IGPM')),
  constraint ck_contratos_data check (data_vencimento >= data_inicio)
);

create table app.faturas_condominiais (
  fatura_id number(19,0) generated by default on null as identity primary key,
  condominio_id number(19,0) not null,
  unidade_id number(19,0) not null,
  morador_id number(19,0),
  competencia date not null,
  vencimento date not null,
  valor_total number(14,2) not null,
  status varchar2(15) not null,
  data_pagamento timestamp,
  origem_dado varchar2(12) default 'api' not null,
  created_at timestamp default systimestamp not null,
  updated_at timestamp default systimestamp not null,
  constraint fk_faturas_condominio foreign key (condominio_id) references app.condominios(condominio_id),
  constraint fk_faturas_unidade foreign key (unidade_id) references app.unidades(unidade_id),
  constraint fk_faturas_morador foreign key (morador_id) references app.moradores(morador_id),
  constraint ck_faturas_valor check (valor_total >= 0),
  constraint ck_faturas_status check (status in ('pending', 'paid', 'overdue')),
  constraint ck_faturas_origem check (origem_dado in ('api', 'mock')),
  constraint uq_faturas_unidade_competencia unique (unidade_id, competencia)
);

create index app.idx_faturas_condominio_comp on app.faturas_condominiais(condominio_id, competencia);
create index app.idx_faturas_status on app.faturas_condominiais(status);

create table app.eventos_anomalia (
  anomalia_sk number(19,0) generated by default on null as identity primary key,
  anomalia_id number(19,0),
  condominio_id number(19,0) not null,
  data_detectada timestamp not null,
  tipo_anomalia varchar2(255) not null,
  entidade_tipo varchar2(100) not null,
  entidade_id number(19,0),
  fornecedor_id number(19,0),
  unidade_id number(19,0),
  gravidade varchar2(15) not null,
  score_anomalia number(6,4),
  descricao_anomalia clob,
  recomendacao_acao clob,
  status_revisao varchar2(20) not null,
  usuario_revisor varchar2(120),
  data_revisao timestamp,
  constraint fk_anomalia_condominio foreign key (condominio_id) references app.condominios(condominio_id),
  constraint fk_anomalia_fornecedor foreign key (fornecedor_id) references app.fornecedores(fornecedor_id),
  constraint fk_anomalia_unidade foreign key (unidade_id) references app.unidades(unidade_id),
  constraint ck_anomalia_gravidade check (gravidade in ('baixa', 'media', 'alta', 'critica')),
  constraint ck_anomalia_status check (status_revisao in ('pendente', 'em_revisao', 'resolvido', 'descartado')),
  constraint ck_anomalia_score check (score_anomalia between 0 and 1)
);

create index app.idx_anomalia_cond_data on app.eventos_anomalia(condominio_id, data_detectada);
create index app.idx_anomalia_status on app.eventos_anomalia(status_revisao);
