-- 004_auth_users.sql
-- Tabela de autenticacao local para ambiente de homolog/dev.

create table app.usuarios (
  usuario_id number(19,0) generated by default on null as identity primary key,
  condominium_id number(19,0),
  email varchar2(255) not null,
  password_hash varchar2(128) not null,
  role varchar2(20) not null,
  active number(1,0) default 1 not null,
  created_at timestamp default systimestamp not null,
  updated_at timestamp default systimestamp not null,
  constraint uq_usuarios_email unique (email),
  constraint ck_usuarios_role check (role in ('admin', 'sindico', 'morador')),
  constraint ck_usuarios_active check (active in (0, 1))
);

create index app.idx_usuarios_email on app.usuarios(email);

insert into app.usuarios (condominium_id, email, password_hash, role, active)
values (1, 'admin@condoguard.ai', standard_hash('password123', 'SHA256'), 'admin', 1);

insert into app.usuarios (condominium_id, email, password_hash, role, active)
values (1, 'sindico@condoguard.ai', standard_hash('password123', 'SHA256'), 'sindico', 1);

insert into app.usuarios (condominium_id, email, password_hash, role, active)
values (1, 'morador@condoguard.ai', standard_hash('password123', 'SHA256'), 'morador', 1);

