-- 010_enel_integration_tables.sql
-- Sprint 9: trilha de execucao da integracao ENEL e evolucao de origem de faturas.

create table app.integracoes_execucoes (
  run_id varchar2(40) primary key,
  condominio_id number(19,0) not null,
  provider varchar2(30) not null,
  source varchar2(40) not null,
  status varchar2(30) not null,
  requested_by varchar2(255),
  started_at timestamp not null,
  finished_at timestamp,
  duration_ms number(19,0),
  total_items number(10,0) default 0 not null,
  imported_items number(10,0) default 0 not null,
  skipped_items number(10,0) default 0 not null,
  failed_items number(10,0) default 0 not null,
  error_summary varchar2(500),
  notes varchar2(500),
  created_at timestamp default systimestamp not null,
  constraint fk_integr_exec_condominio foreign key (condominio_id) references app.condominios(condominio_id),
  constraint ck_integr_exec_status check (status in ('processing', 'completed', 'completed_with_errors', 'failed'))
);

create index app.idx_integr_exec_cond_started on app.integracoes_execucoes(condominio_id, started_at desc);
create index app.idx_integr_exec_status on app.integracoes_execucoes(status);

create table app.integracoes_itens (
  item_sk number(19,0) generated by default on null as identity primary key,
  run_id varchar2(40) not null,
  condominio_id number(19,0) not null,
  item_index number(10,0) not null,
  result varchar2(20) not null,
  reason varchar2(500),
  external_reference varchar2(120),
  unit_code varchar2(30),
  resident_name varchar2(255),
  reference_code varchar2(20),
  due_date date,
  amount number(14,2),
  invoice_status varchar2(15),
  business_key varchar2(240),
  external_hash varchar2(128),
  invoice_id number(19,0),
  created_at timestamp default systimestamp not null,
  constraint fk_integr_item_run foreign key (run_id) references app.integracoes_execucoes(run_id),
  constraint fk_integr_item_condominio foreign key (condominio_id) references app.condominios(condominio_id),
  constraint fk_integr_item_invoice foreign key (invoice_id) references app.faturas_condominiais(fatura_id),
  constraint ck_integr_item_result check (result in ('imported', 'skipped', 'failed')),
  constraint ck_integr_item_invoice_status check (invoice_status in ('pending', 'paid', 'overdue'))
);

create index app.idx_integr_item_run on app.integracoes_itens(run_id, item_index);
create index app.idx_integr_item_dedupe on app.integracoes_itens(condominio_id, business_key, external_hash);

alter table app.faturas_condominiais drop constraint ck_faturas_origem;

alter table app.faturas_condominiais add constraint ck_faturas_origem
check (origem_dado in ('api', 'mock', 'integration_enel'));
