-- 011_sabesp_consumption_tables.sql
-- Sprint 12: persistencia Oracle-first do consumo de agua importado pela SABESP.

create table app.consumo_agua_mensal (
  consumo_agua_id number(19,0) generated by default on null as identity primary key,
  condominio_id number(19,0) not null,
  unidade_id number(19,0) not null,
  referencia varchar2(20) not null,
  data_leitura date not null,
  vencimento date not null,
  consumo_m3 number(14,3) not null,
  valor_total number(14,2) not null,
  status varchar2(15) not null,
  origem_dado varchar2(20) default 'api' not null,
  external_reference varchar2(120),
  business_key varchar2(240) not null,
  external_hash varchar2(128) not null,
  observacoes varchar2(500),
  created_at timestamp default systimestamp not null,
  updated_at timestamp default systimestamp not null,
  constraint fk_cons_agua_cond foreign key (condominio_id) references app.condominios(condominio_id),
  constraint fk_cons_agua_unit foreign key (unidade_id) references app.unidades(unidade_id),
  constraint ck_cons_agua_cons check (consumo_m3 >= 0),
  constraint ck_cons_agua_val check (valor_total >= 0),
  constraint ck_cons_agua_st check (status in ('pending', 'paid', 'overdue')),
  constraint ck_cons_agua_org check (origem_dado in ('api', 'mock', 'integration_sabesp')),
  constraint uq_cons_agua_bkey unique (condominio_id, business_key),
  constraint uq_cons_agua_hash unique (condominio_id, external_hash)
);

create index app.idx_cons_agua_cond_ref on app.consumo_agua_mensal(condominio_id, referencia, data_leitura desc);
create index app.idx_cons_agua_unit_ref on app.consumo_agua_mensal(unidade_id, referencia);

