-- 005_contracts_schema_bootstrap_oracle.sql
-- Safe bootstrap for APP.FORNECEDORES and APP.CONTRATOS when missing.

declare
  l_count number;
begin
  begin
    execute immediate q'[
      create table app.fornecedores (
        fornecedor_id number(19,0) generated by default on null as identity primary key,
        razao_social varchar2(255) not null,
        cnpj varchar2(18),
        cnae_principal varchar2(10),
        data_abertura date,
        status_rfb varchar2(20),
        cidade varchar2(120),
        estado char(2)
      )
    ]';
  exception
    when others then
      if sqlcode != -955 then raise; end if;
  end;

  begin
    execute immediate q'[
      create table app.contratos (
        contrato_id number(19,0) generated by default on null as identity primary key,
        condominio_id number(19,0) not null,
        fornecedor_id number(19,0) not null,
        tipo_servico varchar2(255) not null,
        valor_mensal_vigente number(14,2) not null,
        data_inicio date not null,
        data_vencimento date not null,
        indice_reajuste varchar2(10) not null,
        sla_horas_mensais number(10,2),
        status_auditoria_ia varchar2(120)
      )
    ]';
  exception
    when others then
      if sqlcode != -955 then raise; end if;
  end;

  select count(1) into l_count from app.fornecedores;
  if l_count = 0 then
    insert into app.fornecedores (fornecedor_id, razao_social, cnpj, cidade, estado) values (1, 'Sentinel Security Ltda', '11111111000101', 'Sao Paulo', 'SP');
    insert into app.fornecedores (fornecedor_id, razao_social, cnpj, cidade, estado) values (2, 'LimpaPro Servicos', '22222222000102', 'Sao Paulo', 'SP');
    insert into app.fornecedores (fornecedor_id, razao_social, cnpj, cidade, estado) values (3, 'TechLift Elevadores', '33333333000103', 'Sao Paulo', 'SP');
  end if;

  select count(1) into l_count from app.contratos;
  if l_count = 0 then
    insert into app.contratos (
      contrato_id, condominio_id, fornecedor_id, tipo_servico, valor_mensal_vigente, data_inicio, data_vencimento, indice_reajuste, status_auditoria_ia
    )
    select
      row_number() over (order by base.condominio_id, f.fornecedor_id) as contrato_id,
      base.condominio_id,
      f.fornecedor_id,
      f.tipo_servico,
      round(base.valor_total * f.fator, 2),
      trunc(sysdate),
      add_months(trunc(sysdate), 12),
      f.indice_reajuste,
      case when base.vencidas > 0 then 'atencao' else 'ok' end
    from (
      select condominio_id, nvl(sum(amount), 0) as valor_total, sum(case when lower(status) = 'overdue' then 1 else 0 end) as vencidas
      from mart.vw_financial_invoices
      group by condominio_id
    ) base
    cross join (
      select 1 as fornecedor_id, 'Seguranca patrimonial' as tipo_servico, 0.42 as fator, 'IPCA' as indice_reajuste from dual
      union all
      select 2 as fornecedor_id, 'Limpeza e conservacao' as tipo_servico, 0.32 as fator, 'IGPM' as indice_reajuste from dual
      union all
      select 3 as fornecedor_id, 'Manutencao de elevadores' as tipo_servico, 0.26 as fator, 'IPCA' as indice_reajuste from dual
    ) f;
  end if;

  commit;
end;
/
